[tool.bumpversion]
current_version = "1.0.0"
commit = false
tag = false
allow_dirty = true

[[tool.bumpversion.files]]
filename = "pom.xml"
search = "<version>{current_version}</version>"
replace = "<version>{new_version}</version>"

[[tool.bumpversion.files]]
filename = "README.md"
search = "<version>{current_version}</version>"
replace = "<version>{new_version}</version>"
[[tool.bumpversion.files]]
filename = "README.md"
search = "secrets-manager-instance-management:{current_version}"
replace = "secrets-manager-instance-management:{new_version}"
